<?php

namespace Splio\WatchBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Splio\WatchBundle\Entity\Link;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * [findTagsOfLink description]
     * @param  Link    $link   [description]
     * @param  integer $offset [description]
     * @param  integer $limit  [description]
     * @return [type]          [description]
     */
    public function findTagsOfLink(Link $link, $offset = 0, $limit = 10)
    {
        return $this->createQueryBuilder("t")
            ->innerJoin("t.links", "l", "WITH", "l=:link")
            ->setParameter("link", $link)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
        ->getQuery()->getResult() ;
    }
}
