services:
    splio_rest.request_version_listener:
        class: Splio\RestBundle\EventListener\RequestVersionListener
        calls:
            - [setAcceptPattern, ['%splio_rest.accept_pattern%']]
        tags:
            - {name: "kernel.event_listener", event:"kernel.request", method:"onKernelRequest", priority:"33"}