services:
    splio_rest.base_controller:
        class: Splio\RestBundle\Controller\BaseController
        arguments: []
        calls:
            - [setRouter, ['@router']]
            - [setDebug, ['%kernel.debug%']]

    splio_rest_controller:
        alias: splio_rest.base_controller
