# Controller as service
services:
    splio_watch.default_controller:
        class: Splio\WatchBundle\Controller\DefaultController
        arguments: []
        calls:
            - [setUserService, ["@user_service"]]
            - [setLinkService, ["@link_service"]]

    splio_watch.user_controller:
        class: Splio\WatchBundle\Controller\UserController
        parent: splio_rest.base_controller
        calls:
            - [setUserService, ["@user_service"]]
            - [setUserSerializer, ["@user_serializer"]]
            - [setLinkSerializer, ["@link_base_serializer"]]
            - [setCommandBus, ["@command_bus"]]

    splio_watch.link_controller:
        class: Splio\WatchBundle\Controller\LinkController
        parent: splio_rest.base_controller
        calls:
            - [setLinkService, ["@link_service"]]
            - [setLinkSerializer, ["@link_serializer"]]
            - [setCommandBus, ["@command_bus"]]
            - [setSecurityContext, ["@security.context"]]

    splio_watch.tag_controller:
        class: Splio\WatchBundle\Controller\TagController
        parent: splio_rest.base_controller
        calls:
            - [setTagSerializer, ['@splio_watch.tag_serializer']]
            - [setTagService, ['@splio_watch.tag_service']]
            - [setLinkSerializer, ['@splio_watch.link_serializer']]
            - [setCommandBus, ["@command_bus"]]

    splio_watch.security_controller:
        class: Splio\WatchBundle\Controller\SecurityController
        parent: splio_rest.base_controller
        calls:
            - [setUserService, ['@user_service']]
            - [setUserRepository, ['@user_repository']]
            - [setFrontAppUrl, ['%splio_watch.front_app_url%']]
            - [setGithubAppId, ['%splio_watch.github.application_id%']]
            - [setGithubAppSecret, ['%splio_watch.github.application_secret%']]