services:
    splio_watch.user_service:
        class: Splio\WatchBundle\Service\UserService
        arguments: []
        calls:
            - [setLinkRepository, ["@link_repository"]]
            - [setTagRepository, ["@tag_repository"]]
            - [setUserRepository, ["@user_repository"]]
        tags:
            - { name: command_handler, handles: splio_watch_create_user, method: create }
    user_service:
        alias: splio_watch.user_service

    splio_watch.link_service:
        class: Splio\WatchBundle\Service\LinkService
        arguments: []
        calls:
            - [setTagRepository, ["@tag_repository"]]
            - [setLinkRepository, ["@link_repository"]]
    link_service:
        alias: splio_watch.link_service

    splio_watch.tag_service:
        class: Splio\WatchBundle\Service\TagService
        arguments: []
        calls:
            - [setLinkRepository, ["@link_repository"]]
            - [setTagRepository, ["@tag_repository"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    tag_service:
        alias: splio_watch.tag_service

    splio_watch.link_repository:
        class: Splio\WatchBundle\Entity\LinkRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:Link'
    link_repository:
        alias: splio_watch.link_repository

    splio_watch.tag_repository:
        class: Splio\WatchBundle\Entity\TagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:Tag'
    tag_repository:
        alias: splio_watch.tag_repository

    splio_watch.user_repository:
        class: Splio\WatchBundle\Entity\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:User'
    user_repository:
        alias: splio_watch.user_repository
