services:
    splio_watch.user_service:
        class: Splio\WatchBundle\Service\UserService
        arguments: []
        calls:
            - [setLinkRepository, ["@link_repository"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setTagRepository, ["@tag_repository"]]
            - [setUserRepository, ["@user_repository"]]

    user_service:
        alias: splio_watch.user_service

    splio_watch.link_service:
        class: Splio\WatchBundle\Service\LinkService
        arguments: []
        calls:
            - [setTagRepository, ["@tag_repository"]]
            - [setLinkRepository, ["@link_repository"]]

    link_service:
        alias: splio_watch.link_service

    splio_watch.tag_service:
        class: Splio\WatchBundle\Service\TagService
        arguments: []
        calls:
            - [setLinkRepository, ["@link_repository"]]
            - [setTagRepository, ["@tag_repository"]]

    link_service:
        alias: splio_watch.link_service

    splio_watch.link_repository:
        class: Splio\WatchBundle\Entity\LinkRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:Link'

    link_repository:
        alias: splio_watch.link_repository

    splio_watch.tag_repository:
        class: Splio\WatchBundle\Entity\TagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:Tag'

    tag_repository:
        alias: splio_watch.tag_repository

    splio_watch.user_repository:
        class: Splio\WatchBundle\Entity\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:User'

    user_repository:
        alias: splio_watch.user_repository

    # Controller as service
    splio_watch.default_controller:
        class: Splio\WatchBundle\Controller\DefaultController
        arguments: []
        calls:
            - [setUserService, ["@user_service"]]
            - [setLinkService, ["@link_service"]]

    splio_watch.user_controller:
        class: Splio\WatchBundle\Controller\UserController
        parent: splio_rest.base_controller

    splio_watch.link_controller:
        class: Splio\WatchBundle\Controller\LinkController
        parent: splio_rest.base_controller
        calls:
            - [setLinkService, ["@link_service"]]
            - [setLinkSerializer, ["@link_serializer"]]

    splio_watch.tag_controller:
        class: Splio\WatchBundle\Controller\TagController
        parent: splio_rest.base_controller
        calls:
            - [setTagSerializer, ['@splio_watch.tag_serializer']]

    splio_watch.security_controller:
        class: Splio\WatchBundle\Controller\SecurityController
        parent: splio_rest.base_controller
        calls:
            - [setUserService, ['@user_service']]
            - [setUserRepository, ['@user_repository']]
            - [setFrontAppUrl, ['%splio_watch.front_app_url%']]
            - [setGithubAppId, ['%splio_watch.github.application_id%']]
            - [setGithubAppSecret, ['%splio_watch.github.application_secret%']]

    # Serializers
    splio_watch.link_serializer:
        class: Splio\WatchBundle\Serializer\LinkSerializer
        calls:
            - [setTagSerializer, ['@tag_base_serializer']]
            - [setUserSerializer, ['@user_base_serializer']]

    link_serializer:
        alias: splio_watch.link_serializer

    splio_watch.link_base_serializer:
        class: Splio\WatchBundle\Serializer\LinkBaseSerializer

    link_base_serializer:
        alias: splio_watch.link_base_serializer

    splio_watch.tag_serializer:
        class: Splio\WatchBundle\Serializer\TagSerializer
        calls:
            - [setLinkSerializer, ['@link_base_serializer']]

    tag_serializer:
        alias: splio_watch.tag_serializer

    splio_watch.tag_base_serializer:
        class: Splio\WatchBundle\Serializer\TagBaseSerializer

    tag_base_serializer:
        alias: splio_watch.tag_base_serializer

    splio_watch.user_serializer:
        class: Splio\WatchBundle\Serializer\UserSerializer
        calls:
            - [setLinkSerializer, ['@link_base_serializer']]

    user_serializer:
        alias: splio_watch.user_serializer

    splio_watch.user_base_serializer:
        class: Splio\WatchBundle\Serializer\UserBaseSerializer

    user_base_serializer:
        alias: splio_watch.user_base_serializer