services:
    splio_watch.user_service:
        class: Splio\WatchBundle\Service\UserService
        arguments: []

    user_service:
        alias: splio_watch.user_service

    # Controller as service
    splio_watch.default_controller:
        class: Splio\WatchBundle\Controller\DefaultController
        arguments: []
        calls:
            - [setUserService, ["@user_service"]]

    splio_watch.user_controller:
        class: Splio\WatchBundle\Controller\UserController
        parent: splio_rest.base_controller

    splio_watch.link_controller:
        class: Splio\WatchBundle\Controller\LinkController
        parent: splio_rest.base_controller

    splio_watch.tag_controller:
        class: Splio\WatchBundle\Controller\TagController
        parent: splio_rest.base_controller