services:
    splio_watch.user_service:
        class: Splio\WatchBundle\Service\UserService
        arguments: []
        calls:
            - [setLinkRepository, ["@link_repository"]]

    user_service:
        alias: splio_watch.user_service

    splio_watch.link_service:
        class: Splio\WatchBundle\Service\LinkService
        arguments: []
        calls:
            - [setTagRepository, ["@tag_repository"]]

    link_service:
        alias: splio_watch.link_service

    splio_watch.link_repository:
        class: Splio\WatchBundle\Entity\LinkRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:Link'

    link_repository:
        alias: splio_watch.link_repository

    splio_watch.tag_repository:
        class: Splio\WatchBundle\Entity\TagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'SplioWatchBundle:Tag'

    tag_repository:
        alias: splio_watch.tag_repository

    # Controller as service
    splio_watch.default_controller:
        class: Splio\WatchBundle\Controller\DefaultController
        arguments: []
        calls:
            - [setUserService, ["@user_service"]]
            - [setLinkService, ["@link_service"]]

    splio_watch.user_controller:
        class: Splio\WatchBundle\Controller\UserController
        parent: splio_rest.base_controller

    splio_watch.link_controller:
        class: Splio\WatchBundle\Controller\LinkController
        parent: splio_rest.base_controller

    splio_watch.tag_controller:
        class: Splio\WatchBundle\Controller\TagController
        parent: splio_rest.base_controller