splio_watch:
    resource: "@SplioWatchBundle/Resources/config/routing.yml"
    prefix:   /

splio_rest:
    resource: "@SplioRestBundle/Resources/config/routing.yml"
    prefix:   /

splio_rest_controller:
    resource:   "@SplioRestBundle/Controller"
    type:       annotation
    prefix:   /rest
