splio_authentication:
    resource: "@SplioAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /

splio_rest:
    resource: "@SplioRestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
