security:
    providers:
        wsse:
            id: wsse.user_provider
    encoders:
        Splio\RestBundle\Security\User\UserProvider: sha512
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        home:
            pattern: ^/
            anonymous: ~
        authentication:
            pattern: ^/auth.*
            anonymous: ~
        wsse_secured:
            pattern:   /.*
            stateless: true
            wsse:      true
