security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

security:
    firewalls:
        wsse_secured:
            pattern:   /.*
            wsse:      true